### ISSUE TITLE
I would appreciate more detail in the readme on the tags

### ISSUE THREAD

**Issue by RallyTronics** [Yelnats321/EntityPlus#19]
I don't have a good understanding of their purpose and how to use them in practice.

**Comment by Yelnats321** [comment]
Imagine you are developing a game where the player character and the NPCs all have an inventory component. This component is configurable, but self contained. When the player wants to see what is inside their inventory, a nice GUI pops up that displays that they have potions, weapons, etc. How do we figure out which inventory belongs to the player? Or a more fundamental question, how do we know which entity IS the player? One way of doing this is through a tag. A tag is basically a named bit. Now, when we need to find the player's inventory, we can query it like this: `em.for_each<Inventory, Player>(...)`. The inventory we get back is definitely tied to the player entity, because only the player entity has that tag.

The alternative is to have an empty component, but in that case we waste space by storing these empty components. Consider tags as an optimization over this alternative.

**Comment by RallyTronics** [comment]
Thanks, that's very helpful.
